//CREACIÓN DE BASE DE DATOS

CREATE DATABASE IF NOT EXISTS codesa;
    
USE codesa;

CREATE TABLE IF NOT EXISTS  ROL (ID_ROL int(32) NOT NULL PRIMARY KEY AUTO_INCREMENT,
NOMBRE VARCHAR(50) NOT NULL);

CREATE TABLE IF NOT EXISTS  USUARIO (ID_USUARIO INT(32) NOT NULL PRIMARY KEY AUTO_INCREMENT, 
ID_ROL INT(32) NOT NULL, 
NOMBRE VARCHAR(50) NOT NULL, ACTIVO CHAR NOT NULL,
FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL) );

//INSERSIÓN DE DATOS
INSERT INTO ROL (NOMBRE) VALUES ('ADMINISTRADOR'), ('AUDITOR'), ('AUXILIAR');
